# Generated by Django 4.0.5 on 2022-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_section_tag_article_tag_section_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='tag_name',
            field=models.CharField(default='----', max_length=30, verbose_name='Тэг'),
        ),
    ]
