# Generated by Django 4.0.5 on 2022-06-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionarticle',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='Тэги', to='articles.section'),
        ),
    ]
