# Generated by Django 4.0.5 on 2022-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_sectionarticle_options_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='articles.section', verbose_name='Тэги'),
        ),
    ]
