# Generated by Django 4.0.5 on 2022-06-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статьи'),
        ),
        migrations.AlterField(
            model_name='sectionarticle',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section', verbose_name='Статьи'),
        ),
    ]
