# Generated by Django 4.0.5 on 2022-06-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_sectionarticle_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionarticle',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section', verbose_name='Теги'),
        ),
    ]
