# Generated by Django 4.0.5 on 2022-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_tag_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='scopes', through='articles.SectionArticle', to='articles.section', verbose_name='Тэги'),
        ),
    ]
