# Generated by Django 4.0.5 on 2022-06-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_rename_primary_section_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='some_field',
            field=models.CharField(default='q', max_length=30, verbose_name='test'),
        ),
    ]
