# Generated by Django 4.0.5 on 2022-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_section_some_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='section',
            name='some_field',
        ),
        migrations.AddField(
            model_name='sectionarticle',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
