# Generated by Django 4.0.5 on 2022-06-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='sectionarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='sectionarticle',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.section'),
        ),
    ]
