# Generated by Django 4.0.5 on 2022-06-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_rename_tag_name_section_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionarticle',
            old_name='tags',
            new_name='tag',
        ),
    ]
