# Generated by Django 4.0.5 on 2022-06-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionarticle',
            options={'ordering': ['-is_main', 'tag'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
