# Generated by Django 4.0.5 on 2022-06-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
