# Generated by Django 4.0.5 on 2022-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_student_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeacher',
        ),
    ]
